default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: commuter_dev

test:
  <<: *default
  database: commuter_test


production:
  <<: *default
  database: ddja9d2mmv186l
  username: sbkwpnlfbvwwrd
  password: b90939adec0a0536a90f00654dc5407bbca6d78b405b81581d31cc901ba1cb65
  url: <%= ENV['DATABASE_URL'] %>
