default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: commuter_dev

test:
  <<: *default
  database: commuter_test


production:
  <<: *default
  database: d11h99fic6o86v
  url: <%= ENV['DATABASE_URL'] %>
