default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: commuter_development

test:
  <<: *default
  database: commuter_test

production:
  <<: *default
  database: commuter_production
  username:
  password:
