class Travel < ApplicationRecord

  MRTLINE = "Joo Koon to Pasir Ris/Changi", "Pasir Ris/Changi to Joo Koon", "Jurong East to Marina South Pier", "Marina South Pier to Jurong East", "Harbourfront to Marina Bay", "Marina Bay to Harbourfront", "Bukit Panjang to Chinatown", "Chinatown to Bukit Panjang", "Punggol to Harbourfront", "Harbourfront to Punggol"

  TIMESLOT = "Early Birds 06:00 - 08:00", "Rise & Grind 08:00 - 10:00", "Late Morning 10:00 - 12:00", "Lunch Rush 12:00 - 14:00", "Early Afternoon 14:00 - 16:00", "End of Grind 16:00 - 18:00", "Homeward Bound 18:00 - 20:00", "Night Owls 20:00 - 22:00"

  START_ROUTE = "ADMIRALTY [NS10]", "ALJUNIED [EW9]", "ANG MO KIO [NS10]", "BAKAU [SE3]", "BANGKIT [BP9]", "BARTLEY [CC12]", "BAYFRONT [CE1] [DT16]", "BEAUTY WORLD [DT5]", "BEDOK [EW5]", "BISHAN [CC15] [NS17]", "BOON KENG [NE9]", "BOON LAY [EW27]", "BOTANIC GARDENS [CC19] [DT9]", "BRADDELL [NS18]", "BRAS BASAH [CC2]", "BUANGKOK [NE15]", "BUGIS [DT14] [EW12]", "BUKIT BATOK [NS2]", "BUKIT GOMBAK [NS3]", "BUKIT PANJANG [BP6] [DT1]", "BUONA VISTA [CC22] [EW21]", "CALDECOTT [CC17]", "CASHEW [DT2]", "CHANGI AIRPORT [CG2]", "CHENG LIM [SW1]", "CHINATOWN [DW19] [NE4]", "CHINESE GARDEN [EW25]", "CHOA CHU KANG [BP1] [NS4]", "CITY HALL [EW13] [NS25]", "CLARKE QUAY [NE5]", "CLEMENTI [EW23]", "COMMONWEALTH [EW20]", "COMPASSVALE [SE1]", "CORAL EDGE [PE3]", "COVE PE1", "DAKOTA [CC8]"

    END_ROUTE = "ADMIRALTY [NS10]", "ALJUNIED [EW9]", "ANG MO KIO [NS10]", "BAKAU [SE3]", "BANGKIT [BP9]", "BARTLEY [CC12]", "BAYFRONT [CE1] [DT16]", "BEAUTY WORLD [DT5]", "BEDOK [EW5]", "BISHAN [CC15] [NS17]", "BOON KENG [NE9]", "BOON LAY [EW27]", "BOTANIC GARDENS [CC19] [DT9]", "BRADDELL [NS18]", "BRAS BASAH [CC2]", "BUANGKOK [NE15]", "BUGIS [DT14] [EW12]", "BUKIT BATOK [NS2]", "BUKIT GOMBAK [NS3]", "BUKIT PANJANG [BP6] [DT1]", "BUONA VISTA [CC22] [EW21]", "CALDECOTT [CC17]", "CASHEW [DT2]", "CHANGI AIRPORT [CG2]", "CHENG LIM [SW1]", "CHINATOWN [DW19] [NE4]", "CHINESE GARDEN [EW25]", "CHOA CHU KANG [BP1] [NS4]", "CITY HALL [EW13] [NS25]", "CLARKE QUAY [NE5]", "CLEMENTI [EW23]", "COMMONWEALTH [EW20]", "COMPASSVALE [SE1]", "CORAL EDGE [PE3]", "COVE PE1", "DAKOTA [CC8]"


end
